### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by datastory** [vrtstartup/Social-Video-Tools#33]
After seemingly successful installation and start of server and worker processes app shows only 

> Cannot GET /
![image](https://cloud.githubusercontent.com/assets/2298856/22019892/b94ad45c-dcb5-11e6-9335-6932e9c4a2f9.png)

**Comment by matthiasdv** [comment]
@datastory This is most likely due to the way the app is served; The message you are seeing means the folder being served is empty. The server serves the front-end files from the `/dist` folder. 

In order to build the front-end you can run one of the following npm commands: 

`npm run build-dev`

`npm run build-prod`

These differ in the webpack config file they use (webpack.dev.js and webpack.prod.js respectively). Running one of those commands should yield the missing dist folder. 
 
Alternatively, for development purposes, you can use the webpack development server as follows: 

`npm run dev-server`

Which provides a local development server that proxies outgoing requests to your running node server. This way you don't have to rebuild the front-end app while developing. 


We're still in ongoing development, so all feedback is more than welcome! 


Cheers.
